version: 3
tasks:
  cli:
    cmds:
    - cd cli && go build -o ../machinecfg
  test:
    vars:
      root_opts: --sites=maison --roles=cattle
      netbox_opts: --netbox-endpoint=$NETBOX_ENDPOINT --netbox-token=$NETBOX_TOKEN
      output_opts: --output-directory=tmp

    cmds:
    - ./machinecfg {{.root_opts}} tinkerbell hardware {{.netbox_opts}} {{.output_opts}} --embed-ignition-as-vendor-data=true
    - ./machinecfg {{.root_opts}} butane flatcar {{.netbox_opts}} {{.output_opts}}
    - ./machinecfg {{.root_opts}} talos machineconfig {{.netbox_opts}} {{.output_opts}}

  clean-tmp:
    cmd: rm -rf tmp/*
