version: 3
tasks:
  default:
    desc: Build everything
    cmds:
    - task: cli

  cli:
    desc: Build the CLI binary
    cmds:
    - cd cli && go build -o ../machinecfg

  test:
    desc: Run tests
    deps: [ "cli" ]
    vars:
      root_opts: --sites=maison --roles=cattle
      netbox_opts: --netbox-endpoint=$NETBOX_ENDPOINT --netbox-token=$NETBOX_TOKEN
      output_opts: --output-directory=tmp

    cmds:
    - ./machinecfg {{.root_opts}} tinkerbell hardware {{.netbox_opts}} {{.output_opts}} --embed-ignition-as-vendor-data=true
    - ./machinecfg {{.root_opts}} butane flatcar {{.netbox_opts}} {{.output_opts}}
    - ./machinecfg {{.root_opts}} talos machineconfig {{.netbox_opts}} {{.output_opts}}

  clean-tmp:
    desc: Remove temporary files
    cmd: rm -rf tmp/*
