---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "machinecfg-controller-netbox-updater.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "machinecfg-controller-netbox-updater.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "machinecfg-controller-netbox-updater.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "machinecfg-controller-netbox-updater.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      serviceAccountName: {{ include "machinecfg-controller-netbox-updater.fullname" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/controller-netbox-updater"]
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          env:
            - name: CONTROLLER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LEADER_ELECT
              value: {{ .Values.controller.leaderElect | toString | quote }}
            - name: LIMITS_CPU
              valueFrom:
                resourceFieldRef:
                  containerName: controller
                  resource: limits.cpu
                  divisor: "1"
            - name: LIMITS_MEMORY
              valueFrom:
                resourceFieldRef:
                  containerName: controller
                  resource: limits.memory
                  divisor: "1Mi"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
