---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "machinecfg-controller-netbox-updater.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "machinecfg-controller-netbox-updater.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: /metrics
spec:
  selector:
    {{- include "machinecfg-controller-netbox-updater.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
    - name: health
      port: 8081
      targetPort: health
      protocol: TCP
  type: ClusterIP
