---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "machinecfg-controller-netbox-updater.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "machinecfg-controller-netbox-updater.labels" . | nindent 4 }}
